branches:
  only:
    - master

skip_tags: false

init:
  - git config --global core.autocrlf input

cache:
  - packages -> **\packages.config
  - tools -> build.cake

build_script: 
  - ps: .\build.ps1

artifacts: 
  - path: artifacts
    name: OctopusStyles

deploy:
  - provider: GitHub
    artifact: /.*\.zip/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
